version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./app:/code/app
      - ./requirements.txt:/code/requirements.txt
      - ./.env:/code/.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"